languageCode: en-us
title: ActiveState Platform Documentation
theme: github.com/matcornic/hugo-theme-learn
publishDir: docs
enableGitInfo: true
enableRobotsTXT: true

outputs:
  home: 
  - "HTML"
  - "RSS"
  - "JSON"


markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false